services:
  postgres:
    image: postgres:17
    container_name: paybridge-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - paybridge-data:/var/lib/postgresql/data

volumes:
  paybridge-data:
